title: "iO-Labs - Laboratorio Tecnológico"
email: contacto@io-labs.cl
description: "Capturamos el futuro, Monitoreamos el progreso, tecnología avanzada para un mundo en constante cambio."
keywords: "Laboratorio tecnologico, Servicios de monitoreo, Captura de variables en tiempo real, Monitoreo remoto de líneas de producción, Automatización y control."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

